version: '3.4'

services:
  productdb:
    image: mongo
  product.microservice:
    image: ${DOCKER_REGISTRY-}productmicroservice
    build:
      context: .
      dockerfile: Microservice/Product.Microservice/Dockerfile

volumes:
  mongo_data: